<?php

declare(strict_types=1);

namespace Test\Unit;

use PHPUnit\Framework\TestCase;
use Tree\AdjacencyList;

/**
 * @internal
 */
final class AdjacencyListTest extends TestCase
{
    public AdjacencyList $adjacencyList;
    public AdjacencyList $adjacencyListEmpty;

    public array $input = [
        ['id' => 2, 'parent_id' => 0, 'title' => 'Языки программирования'],
        ['id' => 5, 'parent_id' => 2, 'title' => 'php'],
        ['id' => 6, 'parent_id' => 2, 'title' => 'js'],
        ['id' => 7, 'parent_id' => 6, 'title' => 'Функции'],
        ['id' => 8, 'parent_id' => 7, 'title' => 'DOM'],
        ['id' => 9, 'parent_id' => 8, 'title' => 'Автоматический скролл'],
        ['id' => 10, 'parent_id' => 8, 'title' => 'Подстраивание контента'],
        ['id' => 3, 'parent_id' => 0, 'title' => 'Книги по программированию'],
        ['id' => 4, 'parent_id' => 0, 'title' => 'Курсы по программированию'],
    ];

    protected function setUp(): void
    {
        $this->adjacencyList = new AdjacencyList($this->input, ['parent' => 'parent_id']);
        $this->adjacencyListEmpty = new AdjacencyList([]);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreateRootNodes(): void
    {
        self::assertCount(3, $this->adjacencyList->getRootNodes());
    }

    public function testEmptyNodes(): void
    {
        self::assertCount(0, $this->adjacencyListEmpty->getRootNodes());
    }

    public function testCreate(): void
    {
        $getTree = $this->adjacencyList->getTree();
        /**
         * @psalm-suppress MixedArgument
         */
        self::assertArrayHasKey('children', $getTree[2]);
    }
}
